backend:
  name: github
  repo: herrkaefer/herrkaefer.com
  branch: master
  use_graphql: false
  base_url: https://herrkaefer.com
  auth_endpoint: /api/auth

publish_mode: simple
site_url: https://herrkaefer.com
display_url: https://herrkaefer.com
logo_url: /logo.svg

media_folder: static/assets/images
public_folder: /assets/images

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "-"

x-post-fields: &post_fields
  - label: Title
    name: title
    widget: string
  - label: Date
    name: date
    widget: datetime
    format: YYYY-MM-DD
    date_format: YYYY-MM-DD
    time_format: false
  - label: Year
    name: year
    widget: hidden
    default: "{{year}}"
  - label: Summary
    name: summary
    widget: text
    required: false
  - label: Tags
    name: tags
    widget: list
    required: false
  - label: Categories
    name: categories
    widget: list
    required: false
  - label: Draft
    name: draft
    widget: boolean
    default: true
    required: false
  - label: Body
    name: body
    widget: markdown

x-post-collection-base: &post_collection_base
  folder: content/posts
  search: false
  create: false
  delete: false
  extension: md
  format: frontmatter
  summary: "{{date}} · {{title}}"
  sortable_fields: ["date"]
  sort: "date:desc"
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  editor:
    preview: true
  fields: *post_fields

collections:
  - name: posts
    label: All Posts
    label_singular: Post
    <<: *post_collection_base
    create: true
    delete: true
  - name: posts_2025
    label: "2025"
    label_singular: Post
    <<: *post_collection_base
    filter:
      field: year
      value: "2025"
  - name: posts_2020
    label: "2020"
    label_singular: Post
    <<: *post_collection_base
    filter:
      field: year
      value: "2020"
  - name: posts_2018
    label: "2018"
    label_singular: Post
    <<: *post_collection_base
    filter:
      field: year
      value: "2018"
  - name: posts_2017
    label: "2017"
    label_singular: Post
    <<: *post_collection_base
    filter:
      field: year
      value: "2017"
  - name: posts_2016
    label: "2016"
    label_singular: Post
    <<: *post_collection_base
    filter:
      field: year
      value: "2016"
  - name: posts_2011
    label: "2011"
    label_singular: Post
    <<: *post_collection_base
    filter:
      field: year
      value: "2011"
  - name: posts_2010
    label: "2010"
    label_singular: Post
    <<: *post_collection_base
    filter:
      field: year
      value: "2010"
  - name: posts_2009
    label: "2009"
    label_singular: Post
    <<: *post_collection_base
    filter:
      field: year
      value: "2009"
  - name: posts_2008
    label: "2008"
    label_singular: Post
    <<: *post_collection_base
    filter:
      field: year
      value: "2008"
  - name: posts_2007
    label: "2007"
    label_singular: Post
    <<: *post_collection_base
    filter:
      field: year
      value: "2007"
